### ISSUE TITLE
Wrong weather

### ISSUE THREAD

**Issue by Martinecko30** [sawyerpollard/Minecraft-Weather-New-Tab#1]
Hey bro, I don't think it's entirely functional, as you see here:
![screenshot](https://user-images.githubusercontent.com/52097833/133879758-537a86d9-2c31-452f-b9f4-63cb3a160a74.png) it's showing that it's only clouds but in bottom right corner you can see it's raining. Idc about that 1°C. Only about the weather.
(Sorry for bad English, it's not my native language)

**Comment by Redo122** [comment]
If I had to guess, OpenWeather and whatever Microsoft uses had different information.

**Comment by Martinecko30** [comment]
> If I had to guess, OpenWeather and whatever Microsoft uses had different information.

![image](https://user-images.githubusercontent.com/52097833/133880203-3cb4c54d-4c5d-474a-8e24-9b49f93f26ab.png)
:)

**Comment by Redo122** [comment]
![image](https://user-images.githubusercontent.com/34082999/133880379-c785b12f-66fd-4097-b7d5-b1fd26fdc8fd.png)
what's it like outside?

**Comment by Martinecko30** [comment]
![IMG_20210918_092952](https://user-images.githubusercontent.com/52097833/133880524-d022bcff-a535-4d77-b1bc-07662b02ae8a.jpg)
It stopped raining now but about like 15 minutes ago it was still raining

**Comment by TheBooker66** [comment]
This totally depends on the weather provider.
**Suggestion for the dev**
Add more  weather sites (api) for the end user to choose from.

**Comment by sawyerpollard** [comment]
Hello there, thanks for the feedback! That's very strange that the weather isn't matching what's outside. I suspect this is an issue with OpenWeatherMap's weather data. Additionally, due to limits with OpenWeatherMap, the extension gets new weather every 30 minutes, so it may be 30 minutes delayed. I hope I can improve this in the future.
