### ISSUE TITLE
Small misspell  for "New tab" in spanish

### ISSUE THREAD

**Issue by JpEchev** [sawyerpollard/Minecraft-Weather-New-Tab#28]
Original (aka the good one):
![image](https://user-images.githubusercontent.com/91135478/136589932-c46650b2-f9f9-4737-8f3b-108350c6f248.png)

Current:
![image](https://user-images.githubusercontent.com/91135478/136590095-cc85cc80-2b4c-4696-933b-fe711e33f3c9.png)

I have no idea if this is the right place to drop this little error
Hopefully it is

**Comment by alex-darosa** [comment]
Good catch. I have a question since my Spanish is a little rusty: is "hace buen tiempo" the correct way to say "the weather is nice"?

**Comment by JpEchev** [comment]
> Good catch. I have a question since my Spanish is a little rusty: is "hace buen tiempo" the correct way to say "the weather is nice"?

Sorry for the late reply, but yes, "Hace buen tiempo" would be the correct way to say it

**Comment by sawyerpollard** [comment]
Just updated and gave credit! Thank you!
