### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by Nirmit-Singh** [sawyerpollard/Minecraft-Weather-New-Tab#3]
Any way to display temperature is centigrade instead of Fahrenheit?

**Comment by TheBooker66** [comment]
That is configurable by clicking on the extension (top left of your screen), and selecting Celsius instead of Fahrenheit. The dev also said that in a comment in their reddit post.

**Comment by TheBooker66** [comment]
@Nirmit-Singh If you found my reply helpful, you should close the issue.

**Comment by sawyerpollard** [comment]
> That is configurable by clicking on the extension (top left of your screen), and selecting Celsius instead of Fahrenheit. The dev also said that in a comment in their reddit post.

Thanks! Also, it can sometimes be hidden behind the extensions icon in the top right of Chrome. (The button looks like a puzzle piece.) Click that button and then select the blue creeper face icon to change to Celsius or Fahrenheit.

**Comment by Nirmit-Singh** [comment]
Thanks a lot, great extension
