### ISSUE TITLE
Image Sources

### ISSUE THREAD

**Issue by TheBooker66** [sawyerpollard/Minecraft-Weather-New-Tab#4]
I really don't think it's a good idea to make the image sources curseforge or reddit because those can be easily deleted and can harm the extension. In my opinion, they should be static images you uploaded (for ex. to imgur), with the originals credited in a comment.

**Comment by sawyerpollard** [comment]
Hello there! Fortunately, the images are stored locally in the extension, so Chrome doesn't have to connect to the internet at all to display them. The credit links in the bottom left corner do however link to the remote image sources.

I hope you like the extension!

**Comment by TheBooker66** [comment]
great planning! I was under the impression that every time an the weather changed, the extension would use the link to fetch the new image. Still, for users installing this extension after someone deleted one of the images this could cause a problem. I still suggest making a copy of your own.
