### ISSUE TITLE
Bookmarks and favourite sites not showing with Brave Browser

### ISSUE THREAD

**Issue by MisterCow1** [sawyerpollard/Minecraft-Weather-New-Tab#5]
I'm not sure if this is intentional, but I think you should be able to see your bookmarks when the plugin is enabled

**Comment by sawyerpollard** [comment]
Hello! This has been an issue for me too on Chrome. On Mac, I clicked the "View" menu at the top of Chrome and then selected "Always Show Bookmarks Bar." You may also be able to toggle the bookmarks bar with the keyboard shortcuts `Ctrl + Shift + B` or `Cmd + Shift + B`. It appears that there is a limitation in browser extensions that doesn't allow the bookmarks bar to display on altered New Tab pages.

Let me know if that works. I will investigate further in the future.

**Comment by MisterCow1** [comment]
"Always Show Bookmarks Bar." works on Brave browser. However, is there a way to get favourite sites to show? I believe the plugin hides that as well.

**Comment by GreatSymphonia** [comment]
According to [this](https://stackoverflow.com/questions/33714939/how-show-chrome-bookmarks-bar-on-custom-newtab-page), it is impossible.

**Comment by GreatSymphonia** [comment]
On brave however, I am not sure, I'll do further testing

**Comment by GreatSymphonia** [comment]
Yes, everything's hidden, to always show bookmarks seems to be the solution.

**Comment by MisterCow1** [comment]
Ok, thank you

**Comment by GreatSymphonia** [comment]
No problem, I think you can close your issue

**Comment by MisterCow1** [comment]
Yes, thanks for the help
