### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by GreatSymphonia** [sawyerpollard/Minecraft-Weather-New-Tab#7]
I would really enjoy it if we could localise the text shown (maybe being able to edit a JSON file with the text string equivalences)

**Comment by sawyerpollard** [comment]
Hi,
I am researching localization options for Chrome Extensions. It's awesome that you were able to localize some of it into French for personal use!

**Comment by GreatSymphonia** [comment]
Actually, a way of doing this would be to have a setting such as for the Celsius/Fahrenheit thing with references to a "localisation JSON" where we would get the references string from.  Add to that a call to the Google API to get the user's system language and that would be it I think.

I'm pretty busy as of right now (University and other personal projects) and that would be one of my first contributions to GitHub, but I would be willing to give it a try when I'll have a bit more time.

**Comment by sawyerpollard** [comment]
I noticed you submitted a pull request, which I will respond to this weekend. So I'll close this issue for now, since it seems we have an implementation in the works.
